import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/blackmarket.module.css'

export default function blackmarket() {
  return <div>
  <div className={styles.body}></div>
  <div className={styles.container}>
  <Head>
    <title>Crident RP: BlackMarket</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={styles.main}>
    <h1 className={styles.title}>
      BlackMarket
    </h1>

    <p className={styles.striped}></p>
        <p>
        <code>Logging Into Mainframe............ DONE!</code>
        <br></br>
        <code>Establishing Connection............ DONE!</code>
        <br></br>
        <code>AES-256 Bypass............ SUCCESS!</code>
        <br></br>
        <code>Hacking Credentials.......... SUCCESS!</code>
        <br></br>
        <code>HACKING COMPLETE</code>
    </p>
    <p className={styles.striped}></p>

  </main>
  </div>
  </div>
}