import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function donate() {
  return <div>
  <div className={styles.container}>
  <Head>
    <title>Crident RP: Donation</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={styles.main}>
    <h1 className={styles.title}>
      Crident Roleplay Donate
    </h1>
    <br></br>
    <br></br>
    <br></br>
    <p className={styles.title}>
      You Can Donate <a href='https://shorturl.at/nHV28'>Here!</a>
    </p>

  </main>
  </div>
  </div>
}
