import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'

const postal1 = 69

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Crident RP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cfx.re/join/rpplrx">Crident Roleplay!</a>
        </h1>

        <p className={styles.description}>
          Enjoy Your Roleplay, Join Us Today!
        </p>

        <div className={styles.grid}>
          <a href="donate.js" className={styles.card}>
            <h2>Donate &rarr;</h2>
            <p>Helps our server develop and keeps the coffee maker going!</p>
          </a>

          <a href="rules.js" className={styles.card}>
            <h2>Rules &rarr;</h2>
            <p>Learn and understand our community guidelines! It Helps Everyone!</p>
          </a>
        </div>

        <p className={styles.striped}></p>
        <p><code>Business End JSON / Usage: Embed Forms</code></p>

        <div className={styles.grid}>
          <a href="traffic.js" className={styles.card}>
            <h2>tr4ffic-garage-form &rarr;</h2>
            <p>Order Form For TR4FFIC Garage</p>
              <br></br>
              <br></br>
              <p>Visit Postal <code>{postal1}</code> Today!</p>
          </a>

          <a href="blackmarket.js" className={styles.card}>
            <h2>blackmarket-orders &rarr;</h2>
            <p><code>
              Establishing Connection... DONE!
              AES-256 TCP... DONE!
              Rerouting DNS... DONE!
              </code></p>
          </a>
        </div>

      </main>
    </div>
  )
}
