import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

function rules() {
  return <div>
  <div className={styles.container}>
  <Head>
    <title>Crident RP: Rules</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={styles.main}>
    <h1 className={styles.title}>
      Crident Roleplay Rules
    </h1>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <p className={styles.title}>
      You Can View The Server Rules <a href='https://docs.google.com/document/d/1aYvpmO0WrVYek51N-rve416WhlvnqgejfdkMK2y7gKo/edit?usp%F0%9F%98%92haring#heading=h.o6a4r6v8t3sg'>Here!</a>
    </p>
    <br></br>
    <br></br>
    <br></br>
    <p className={styles.title}>
      You Can View The Gang Rules <a href='https://docs.google.com/document/d/10ts3MFCBTTP537OWtA6whacgQnX1vzYfBmMWjxmcx5g/edit?usp=sharing'>Here!</a>
    </p>

  </main>
  </div>
  </div>
}

export default rules
