import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/traffic.module.css'

export default function traffic() {
  return <div>
  <div className={styles.container}>
  <Head>
    <title>Crident RP: TR4FFIC</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={styles.main}>
    <h1 className={styles.titletraffic}>
      TR<span className={styles.trafficred}>4</span>FFIC
    </h1>

  </main>
  </div>
  </div>
}